name=DMXUART
version=4.0.3
author=Richard Case, Case Solved
maintainer=Case Solved
sentence=ESP8266 and ESP32 DMX UART transmit and receive library.
paragraph=DMX512 UART implementation extending Arduino HardwareSerial.
category=Communication
url=https://github.com/casesolved-co-uk/DMXUART
architectures=esp8266,esp32
